version: "3.9"
services:
  app:
    build: .
    image: exo-eval:1.0.0
    depends_on:
      - maria_db
    ports:
      - "5000:5000"
    environment:
      SAVE_DB: "true"
      DB_HOST: maria_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: ismail_test_db

  maria_db:
    image: mariadb:10.5
    ports:
      - 3306:3306

    restart: on-failure

    volumes:
      - .:/var/lib/mysql
