version: "3.9"
services:
  app:
    build: .
    image: exo-eval:1.0.0
    depends_on:
      - maria_db
    ports:
      - "5000:5000"
    environment:
      SAVE_DB: "True"
      DB_HOST: maria_db
      DB_PORT: 3306
      DB_USER: toto
      DB_PASS: titi
      DB_NAME: ismaildb

  maria_db:
    image: mariadb/server:10.3
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/
