FROM python:3.11-alpine

# je spécifie le répertoir du travail  dans le conteneur
WORKDIR /app

COPY requirements.txt  .
COPY templates/index.html .
# j'installe les dépendances:
RUN pip install -r requirements.txt

# j'ajoute l'appli dans le rép du travail.
COPY app.py .
# la startup command , ou commande de démarrage.
CMD ["python", "app.py"]
